"""initial migration

Revision ID: 1d23c9eae9dc
Revises: 
Create Date: 2026-04-05 20:28:33.827662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d23c9eae9dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tasks')
    # op.drop_index(op.f('email'), table_name='users')
    # op.drop_index(op.f('username'), table_name='users')
    # op.drop_table('users')
    # op.drop_table('projects')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('projects',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    # sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    # sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    # sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_user'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_unicode_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('users',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    # sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    # sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    # sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    # sa.Column('birthdate', sa.DATE(), nullable=True),
    # sa.Column('contact_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    # sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    # sa.Column('is_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    # sa.Column('verification_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('code_expire_time', mysql.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_unicode_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index(op.f('username'), 'users', ['username'], unique=True)
    # op.create_index(op.f('email'), 'users', ['email'], unique=True)
    # op.create_table('tasks',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('task_index', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    # sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    # sa.Column('due_date', mysql.DATETIME(), nullable=True),
    # sa.Column('status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    # sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    # sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    # sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_task_project'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_unicode_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # ### end Alembic commands ###
    pass
